django_forest/apps.py
=> chore: readd missing apps.py file

README.md
=> chore: fix README code climate badge

README.md
=> chore: fix README contribute test

README.md
=> chore: add github actions badge

.codeclimate.yml, django_forest/utils/collection.py, django_forest/utils/schema.py
=> chore: fix duplication

.github/workflows/build.yml
=> test: test coverage debug

.github/workflows/build.yml
Reverts ForestAdmin/django-forest#14
=> Revert "test: test coverage debug"

.github/workflows/build.yml, README.md
=> test: test main branch deploy

README.md
=> style: fix broken images

.github/workflows/build.yml, .releaserc.js, package.json
=> chore: fix semantic release

.github/workflows/build.yml, .releaserc.js, package.json
Reverts ForestAdmin/django-forest#18
=> Revert "chore: fix semantic release"

.github/workflows/build.yml, .releaserc.js, package.json
=> chore: fix release

.github/workflows/build.yml, .releaserc.js, package.json, yarn.lock
=> test: fix release

.releaserc.js
=> feat: publish on pypi test repository

setup.cfg
=> fix: fix setup.cfg

.github/workflows/build.yml
=> chore: cache pip dependencies

django_forest/apps.py, django_forest/tests/utils/test_cors.py, django_forest/tests/utils/test_get_forest_setting.py, django_forest/utils/cors.py, django_forest/utils/forest_api_requester.py, django_forest/utils/get_forest_setting.py, django_forest/utils/models.py, django_forest/utils/schema/__init__.py
=> chore: add cors

django_forest/apps.py
=> style: disable url warning for development

django_forest/tests/fixtures/schema.py, django_forest/tests/utils/test_schema.py, django_forest/utils/schema/__init__.py
=> chore: support new schema meta

requirements.txt, setup.cfg
=> chore: update dependencies

requirements.txt, setup.cfg
=> chore: fix version for python version < 3.8

django_forest/tests/actions/hooks/views/test_change.py, django_forest/tests/actions/hooks/views/test_load.py, django_forest/tests/fixtures/schema.py, django_forest/tests/forest/choice.py, django_forest/tests/resources/views/list/test_list_smart_fields.py, django_forest/tests/utils/test_collection.py, django_forest/tests/utils/test_schema.py
=> chore: fix tests after table_name transformation

django_forest/middleware/__init__.py, django_forest/middleware/ip_whitelist.py, django_forest/tests/middleware/__init__.py, django_forest/tests/middleware/test_ip_whitelist.py, django_forest/tests/middleware/test_permissions.py, django_forest/tests/resources/associations/views/test_count.py, django_forest/utils/ip_whitelist.py, django_forest/utils/middlewares.py, requirements.txt, setup.cfg
=> chore: ip whitelist support

django_forest/tests/utils/test_forest_api_requester.py, django_forest/tests/utils/test_schema.py, django_forest/utils/schema/__init__.py
=> chore: handle no content server response on apimap

django_forest/tests/fixtures/schema.py, django_forest/utils/schema/validations.py
=> chore: disable validations for arrayField for now

.github/workflows/build.yml, .releaserc.js, package.json, yarn.lock
⚠️ Before merging this PR you need to put a `PYPI_TOKEN` as a secrets to the github repository!
You can get your `PYPI_TOKEN` on https://pypi.org/
=> chore: add release process

.github/workflows/build.yml, .releaserc.js, package.json, yarn.lock
⚠️ Before merging this PR you need to put a `SLACK_WEBHOOK` as a secrets to the github repository!
=> chore: slack bot setup

setup.cfg
=> chore: rename project to django-forestadmin

README.md, django_forest/tests/fixtures/schema.py, django_forest/tests/utils/test_schema.py, django_forest/utils/schema/__init__.py, setup.cfg
Add missing `__init__.py` file for including python package in final release on pypi
=> fix: add missing actions package in final release + use django-forestadmin as agent name

.releaserc.js, django_forest/utils/schema/version.py
=> fix: correctly set version for schema

django_forest/middleware/permissions.py, django_forest/resources/utils/format.py
=> fix: fix update one to one after new permission middleware

django_forest/tests/forest/question.py, django_forest/utils/views/base.py
=> fix: fix get ids from request with smart action

django_forest/utils/permissions/utils.py
=> fix: fix stats permissions

.gitignore, requirements.txt, setup.cfg
It's never a good thing to use a package install by another dependency. We always have to add it in our requirements to avoid future issues.
=> fix(onboarding): avoid issues if our required packages change their dependencies

django_forest/tests/utils/test_cors.py, django_forest/utils/cors.py
it's not a good idea to use localhost as allowed origins and it's not usefull in our case
=> fix(onboarding): improve the cors settings to allow more onboarding

.pre-commit-config.yaml, requirements.txt, setup.cfg, tox.ini
Add tox to run our tests with all supported python version
=> chore(deps): add pre-commit and tox to improve the development workflow

django_forest/tests/utils/test_cors.py, django_forest/utils/cors.py
we need to send cooki in our cross domain requests
=> fix(cors): allow_crential is mandatory

django_forest/utils/__init__.py, django_forest/utils/type_mapping.py
All the related field hasn't get_accessor_name method
=> fix(apimap): fix the way to retrieve the related field name and the internal type

django_forest/resources/utils/json_api_serializer.py, django_forest/tests/utils/test_json_api_schema.py, django_forest/utils/schema/json_api_schema.py
=> fix(jsonapi): fix the way to retrieve the primary key

django_forest/resources/utils/json_api_serializer.py, django_forest/resources/utils/query_parameters.py, django_forest/resources/utils/queryset/limit_fields.py, django_forest/resources/views/detail.py, django_forest/tests/resources/views/list/test_list_search.py
The serializer raised an exception in some cases (Hidden fields etc.)
=> fix(jsonapiserializer): fix and refactor the jsonapiserializer

django_forest/utils/schema/json_api_schema.py
JsonField should be map to marshmallow's field Raw instead of dict
=> fix(serializer): the jsonfield's serializing returned an error

django_forest/utils/schema/validations.py
The django validators hasn't a code attribute everytime (DecimalValidator).
=> fix(apimap): apimap init crashed the agent with some kinds of validators

.github/workflows/build.yml, requirements.txt, setup.cfg, tox.ini
The agent may now be run on Django4 and python3.10
=> feat(django): add the version 4 of Django as a supported version

django_forest/authentication/oidc/client_manager.py, django_forest/authentication/views/index.py
debug should be easier with some logs
=> fix(authentication): add some logs in the authentication process

django_forest/utils/schema/validations.py
in some case, the project may use custom fields that don't define all the mandatory attributes. we must use default value instead of raise an error
=> fix(onboarding): won't raised error with custom field

django_forest/utils/schema/json_api_schema.py
use the django get_prep_value method to retrieve the good type (usefull with custom field
=> fix(jsonapi): the schema cast the value to the good type

django_forest/resources/utils/decorators.py, django_forest/resources/utils/queryset/search.py, django_forest/tests/resources/views/list/test_list_search.py
uses icontains lookup instead of contains lookup
=> fix(resource): the search behavior must be insensitive

django_forest/resources/utils/queryset/filters/utils.py, django_forest/tests/resources/views/list/test_list_filters.py
uses insensitive lookup instead of sensitive lookup
=> fix(resource): the filter behavior must be insensitive

django_forest/tests/utils/test_cors.py, django_forest/utils/cors.py
implement a new middleware to handle pna headers
=> feat(cors): add the pna preflight headers to handle the last chrome versions

django_forest/middleware/ip_whitelist.py, django_forest/middleware/permissions.py
to ease the debugging we had the reason of the 403
=> fix(403_error): add some content about the reason of the 403 raising

django_forest/resources/utils/csv.py
the model's pk may have another name than 'id'
=> fix(csv): prevent error with model without id attr

django_forest/utils/schema/json_api_schema.py, django_forest/utils/type_mapping.py
=> fix(field_type): dateonly field type should not be in camel case

django_forest/authentication/views/callback.py, django_forest/middleware/permissions.py, django_forest/tests/authentication/views/test_callback.py, django_forest/tests/middleware/test_permissions.py
=> fix(chart): disables the permission middleware for the chart's resources and some roles

django_forest/resources/utils/queryset/filters/utils.py
dateonly filters may be sent as datetime string or date string by the front...
=> fix(filters): date and dateonly fields should be cast to avoid issues in filters

django_forest/resources/utils/csv.py
=> fix(csv): prevent error with model without id attribute

django_forest/resources/utils/json_api_serializer.py
=> fix(smart-relationship): smart relationships are now correctly serialized

django_forest/resources/utils/queryset/filters/utils.py, django_forest/tests/resources/views/list/test_list_filters.py
=> fix(filters): nested aggregator weren't implemented

django_forest/stats/views/stats_with_parameters/__init__.py, django_forest/tests/stats/views/test_stats_with_parameters.py
=> fix(stats): users should be able to use related field in group by aggregation

django_forest/middleware/deactivate_count.py, django_forest/tests/resources/associations/views/test_count.py, django_forest/tests/resources/views/test_count.py
=> fix(ressources): deactivate count didn't return correct value when enable

django_forest/tests/utils/test_middlewares.py, django_forest/utils/middlewares.py
=> fix(middleware): users can force the forest middleware orders

django_forest/tests/resources/views/list/test_list_scope.py, django_forest/utils/scope.py
=> fix(scope): allows users to filter on integer field

.github/workflows/build.yml, setup.cfg
=> feat: package is installable for python3.11

.github/workflows/build.yml, requirements.txt, setup.cfg, tox.ini
=> feat(django_new_version): add support for django 4.1 and 4.2

django_forest/utils/schema/__init__.py
=> fix(forest_init): stop crashing if forestadmin-schema.json doesnt exists in production mode

django_forest/actions/hooks/views/utils.py, django_forest/resources/associations/views/count.py, django_forest/resources/associations/views/csv.py, django_forest/resources/associations/views/list.py, django_forest/resources/utils/resource.py, django_forest/resources/views/csv.py, django_forest/resources/views/detail.py, django_forest/resources/views/list.py, django_forest/stats/utils/stats.py, django_forest/utils/views/action.py
=> fix(debug): add stacktraces when errors occurs

django_forest/actions/hooks/views/utils.py, django_forest/resources/associations/views/count.py, django_forest/resources/associations/views/csv.py, django_forest/resources/associations/views/list.py, django_forest/resources/utils/decorators.py, django_forest/resources/utils/resource.py, django_forest/resources/views/csv.py, django_forest/resources/views/detail.py, django_forest/resources/views/list.py, django_forest/stats/utils/stats.py, django_forest/tests/resources/views/list/test_list_search.py, django_forest/utils/views/action.py
=> fix(edit_belongs_to): fix search on belongsTo widget when editing

django_forest/resources/utils/json_api_serializer.py
=> fix(many_to_many): fix error getting autogenerated model

django_forest/resources/utils/smart_field.py
=> fix(smart_field): a smart field can now be used as reference_field

django_forest/resources/utils/smart_field.py
=> fix(smart_field): don't try to compute smart fields on null relations

django_forest/resources/utils/smart_field.py, django_forest/tests/forest/__init__.py, django_forest/tests/forest/place.py, django_forest/tests/resources/views/list/test_list_smart_fields.py, django_forest/tests/utils/test_schema.py
=> fix(smart_fields): don't compute smart field on null relations

django_forest/resources/utils/queryset/__init__.py, django_forest/resources/utils/queryset/live_query_segment.py, django_forest/resources/utils/queryset/segment.py, django_forest/tests/resources/views/list/test_list_live_query_segment.py
=> fix(segments): add an util to handle live query
